{{- $secret := (include "cronjobs.imageSecrets" .) -}}
{{- if ne $secret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker
  labels:
    {{- include "cronjobs.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $secret }}
{{- end -}}
